### ISSUE TITLE
So many errors

### ISSUE THREAD

**Issue by Guna-not** [Tsaihemanth150/hackersite#12]
First it was easy_pdf module not found, and now itss say makemigrations module not found,  and hackersite module not found error

**Comment by Tsaihemanth150** [comment]
Hi @Guna-not ,
we have forgot addd three pacakes in requirements.txt
django-recaptcha==2.0.6
django-easy-pdf
django-widget-tweaks
please install them and try it 
Thank you

**Comment by Tsaihemanth150** [comment]
@Guna-not , if you still facing isuuse in Running py manage.py makemigrations.
please post error in this thread or attach screenshot

**Comment by Guna-not** [comment]
If i have any problem can you please help me faster? Like can i get any medium to contact you please?

**Comment by Tsaihemanth150** [comment]
@Guna-not , please post here if you need any help will respond ASAP

**Comment by Guna-not** [comment]
Okay
